---
language: python

env:
  global:
    - HELM_URL=https://storage.googleapis.com/kubernetes-helm
    - HELM_TGZ=helm-v2.9.1-linux-amd64.tar.gz
    - TARGET_BR=gh-pages
    - REPO_DIR=/home/travis/build/odavid/k8s-helm-charts
    - GH_URL=https://odavid.github.io/k8s-helm-charts
    - YAMLLINT_VERSION=1.11.1

before_install:
  - >-
    openssl aes-256-cbc
    -K $encrypted_87c45dfd716f_key
    -iv $encrypted_87c45dfd716f_iv
    -in .ssh-keys/travis.enc
    -out .ssh-keys/travis -d
  - chmod 600 .ssh-keys/travis
  - eval $(ssh-agent -s)
  - ssh-add .ssh-keys/travis

install:
  # Installing Helm
  - wget -q ${HELM_URL}/${HELM_TGZ}
  - tar xzfv ${HELM_TGZ}
  - PATH=`pwd`/linux-amd64/:$PATH
  - helm init --client-only
  # Installig pip deps
  - pip install yamllint=="${YAMLLINT_VERSION}"

script:
  # Check charts format
  - >
     for dir in `ls ${REPO_DIR}/charts`; do
      helm lint ${REPO_DIR}/charts/$dir
      if [ $? != 0 ]; then
       travis_terminate 1
      fi
     done
  # Check YAML styling
  - yamllint -c .yamllint.yml -s .travis.yml .yamllint.yml
  - yamllint -c .yamllint.yml -s $(find . -type f -name "Chart.yaml")
  - yamllint -c .yamllint.yml -s $(find . -type f -name "values.yaml")
