apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "my-bloody-jenkins.fullname" . }}
data:
  jenkins-config.yml: |-
    ---
{{- if .Values.managedConfig }}
{{ toYaml .Values.managedConfig | indent 4}}
{{ end }}